// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
    	// prettier-ignore
    	const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:357c7031-f41b-4338-8050-e08016dc9558",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_tL1TLNNoX",
    "aws_user_pools_web_client_id": "3ninqaoue56scegnkrrqvrh9q0",
    "oauth": {
        "domain": "kl-dev-auth.auth.ap-northeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost/",
        "redirectSignOut": "http://localhost/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "kl-dev-api-v1",
            "endpoint": "https://1xy4lbm436.execute-api.ap-northeast-1.amazonaws.com/dev/v1",
            "region": "ap-northeast-1"
        },
        {
            "name": "kl-dev-cdn-v1",
            "endpoint": "https://1xy4lbm436.execute-api.ap-northeast-1.amazonaws.com/dev/cdn/v1",
            "region": "ap-northeast-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://q3owfeaepfeodon52sz65mmrlm.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "kl-dev-file",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "kl-dev-cms",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "kl-dev-src"
};
    	export default awsmobile;
    	